.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching func_80000470, 0x18

glabel func_80000470
    /* 1F70 80000470 3C088000 */  lui        $t0, %hi(D_80000488)
    /* 1F74 80000474 25080488 */  addiu      $t0, $t0, %lo(D_80000488)
    /* 1F78 80000478 01044020 */  add        $t0, $t0, $a0 /* handwritten instruction */
    /* 1F7C 8000047C 8D020000 */  lw         $v0, 0x0($t0)
    /* 1F80 80000480 03E00008 */  jr         $ra
    /* 1F84 80000484 00000000 */   nop
endlabel func_80000470

nonmatching D_80000488

dlabel D_80000488
    /* 1F88 80000488 02010202 */ .word 0x02010202 /* invalid instruction */
    /* 1F8C 8000048C 0C007830 */ .word 0x0C007830
    /* 1F90 80000490 02030204 */ .word 0x02030204 /* invalid instruction */
    /* 1F94 80000494 00000000 */ .word 0x00000000
    /* 1F98 80000498 00000000 */ .word 0x00000000
    /* 1F9C 8000049C 00000000 */ .word 0x00000000
enddlabel D_80000488
